### ISSUE TITLE
Browser Links not opening in Overwolf Browser

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/WoW-Info#17]
Overwolf reviewed the last version and found that external links did not open in the Overwolf Broser but in the user's browser instead.

**Comment by royb3** [comment]
Why is this? Is it not about the comment that it doesn't open links in OW browser? I think that's a item in manifest.

**Comment by royb3** [comment]
Removing `"force_browser": "user",` from the manifest causes the links to be opened in the overwolf browser, you told me to wait with that untill discussed with overwolf team.

**Comment by Arco-Dielhof** [comment]
OW mentioned that it is not too breaking to refuse the app. Until they force other apps to do the same, we can keep doing it the way everyone else does as well.
