### ISSUE TITLE
Clear All button does not work.

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/WoW-Info#20]
The "Clear all!" button does not work in desktop mode.
 
Steps to reproduce:
1. Launch WoW Info.
2. Click the "Composition Builder" button on the top left.
3. In any of the groups, click one of the slots, and select a role.
4. Examine the Statistics information behavior.
5. Click the "Clear All!" button on the bottom.
 
Expected result:
Statistics change according to the selected roles. After clicking the "Clear All!" button, all of the stats reset to 0.
 
Actual result:
Statistics change according to the selected roles. After clicking the "Clear All!" button, nothing changes.

Critical Severity

**Comment by royb3** [comment]
Fixed and committed to main branch, please verify.
