### ISSUE TITLE
Logs error

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/WoW-Info#21]
Please check the logs, as we found the following errors:

desktop.html.1:
ERROR) </js/desktop.js> (:1260) - Uncaught TypeError: Cannot set property 'innerHTML' of null

**Comment by Arco-Dielhof** [comment]
https://drive.google.com/file/d/14rvOQnIGorIup18Ob82045GVhy9TTaWU/view

**Comment by royb3** [comment]
Was related to Clear button issue, is fixed and committed to main.
