### ISSUE TITLE
Add text to Group Applicants

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/WoW-Info#26]
- [x] Add text about needing to be online + having an active LFG open to use this feature.
- [x] Remove that text when LFG is opened.

Text to add:
"You need to be logged in and have an active LFG open in order to use this feature. When you do, your applicants will show in here!"

**Comment by royb3** [comment]
Is removed when first person applies. Don't get empty list when group is created.

Todo: You and I verified it is working, but the text does not look very pretty yet.
